### ISSUE TITLE
App crashes when returning to app after re-allowing the app camera access

### ISSUE THREAD

**Issue by yann1ckv** [gertjaap/vertwallet-ios#35]
After, when it first asked, not giving the app access to my camera on my iPhone X, and then, after trying to give the app access to the camera again, upon returning to the app, it keeps exiting. Closing off the app completely also does not work.
[IMG_4883.MOV.zip](https://github.com/gertjaap/vertwallet-ios/files/1569596/IMG_4883.MOV.zip)

**Comment by yann1ckv** [comment]
Reinstalling the app made it work again. But following exactly the same steps results in the same issue

**Comment by gertjaap** [comment]
This seems to be a generic crash not particularly related to the camera settings. I have fixed various crash reports, hopefully this includes yours. Since i can not reproduce your issue, please verify this again in the next test release and feel free to reopen if not fixed.

In that case, please make a recording of your steps from the install all the way to the crash so i can be aware of the exact steps to take.

Thanks.
